# Why it's necessary: This is the control center. Instead of hardcoding 
# your passwords and regions directly into your Java files (which is a massive security risk),
#  you store them here.


# Server settings backend server will run on http://localhost:8080
server.port=${PORT:8080}

# AWS Credentials and Region
aws.accessKeyId=${AWS_ACCESS_KEY_ID:your_access_key}
aws.secretKey=${AWS_SECRET_ACCESS_KEY:your_secret_key}
aws.region=${AWS_REGION:eu-north-1}
aws.dynamodb.tableName=${AWS_DYNAMODB_TABLE:ir_cracks_detection}


# AWS IoT Core MQTT Broker Configuration
aws.iot.broker.url=${AWS_IOT_BROKER_URL:ssl://a141eqbs4ue48l-ats.iot.eu-north-1.amazonaws.com:8883}
aws.iot.broker.clientId=${AWS_IOT_CLIENT_ID:client01-backend}
aws.iot.topic.filter=${AWS_IOT_TOPIC_FILTER:$share/raid-backend-group/railway/cracks}